name: build lambda_monitoring
on: push
defaults:
  run:
    shell: bash
jobs:
  build:
    name: build lambda_monitoring
    runs-on: ubuntu-latest

    concurrency:
      group: ci-pipeline-${{ github.ref }}
      cancel-in-progress: true

    permissions:
      id-token: write  # Allow OIDC token access
      contents: read   # Allow reading repository contents

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetches all history for all tags and branches

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH  # Ensure uv is in PATH

      - name: Set up Python environment
        run: |
          uv venv .venv --python=3.13  # Change version if needed
          source .venv/bin/activate

      - name: Install dependencies
        run: |
          source .venv/bin/activate
          uv pip install build twine

      - name: Update version
        run: ./update_version.py

      - name: Build package
        run: |
          source .venv/bin/activate
          uv build

      - name: Push package
        run: |
          source .venv/bin/activate
          twine upload --repository pypi dist/*.whl

      - name: Wait for publish
        run: ./wait_for_publish.sh

#  trigger_layers:
#    name: trigger layers pipeline
#    needs: build
#    runs-on: ubuntu-latest
#    strategy:
#        matrix:
#          item:
#          - banking
#          - hive
#          - letsencrypt
#          - mailbackup
#          - monitoring
#          - monty
#          - reddit
#          - sieve
#          - sms2fa
#          - tracker
#          - updates
#
#    steps:
#      - name: Send Repository Dispatch
#        run: |
#          curl -X POST -H "Accept: application/vnd.github.v3+json" \
#          -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
#          https://api.github.com/repos/m4rkw/${{ matrix.item }}/dispatches \
#          -d '{"event_type": "run_pipeline", "client_payload": { "ref": "${{ github.ref }}", "source": "lambda_monitoring" }}'
